
[brick]
authors = ["nikhil.padmanabhan@gmail.com"]
name = "mklRandom"
version = "0.1.0"
chplVersion = "1.19.0"
compopts='--ldflags "-Wl,--no-as-needed" -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl'

[dependencies]


[external]